trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'demos'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: stt/Dockerfile