trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'demos'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: containerRegistry
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: stt/Dockerfile